Expense/urls.py
from django.urls import path
from .import views as v


urlpatterns = [
     path("add",v.addexpense,name="addexpense"), 
     path("details",v.details,name="expdetails"), 
      path("del/<int:incid>",v.delete,name="delete"),
     path("edit/<int:incid>",v.edit,name="edit")   
]

Income/urls.py
from django.urls import path
from .import views as v


urlpatterns = [
     path("add",v.addincome,name="addincome"),
     path("details",v.details,name="incdetails"),
     path("del/<int:incid>",v.delete,name="delete"),
     path("edit/<int:incid>",v.edit,name="edit")     
]

account/urls.py
from django.urls import path
from .import views as v


urlpatterns = [
    path("reg",v.register,name="register"),
    path("login", v.loginn,name="login"),
    path("logout", v.logoutt,name="logout")    
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home),   
    path("Acc-",include(("account.urls","account"),namespace="account")),
    path("Inc-",include(("Income.urls","Income"),namespace="income")) ,
    path("Exp-",include(("Expense.urls","Expense"),namespace="expense"))                           
]

Expense/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

class Expense(models.Model):
    expense=models.IntegerField()
    expense_type=models.CharField(max_length=30)
    expense_date=models.DateField()
    description=models.TextField(max_length=40)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table="expense"


class expenseform(forms.ModelForm):
    class Meta:
        model=Expense
        fields="__all__"




Income/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms


class Income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    income_date=models.DateField()
    description=models.TextField(max_length=40)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table='Income'


#class incomeform(forms.Form):
    #income=forms.IntegerField()
    #income_type=forms.CharField(max_length=30)
    #income_date=forms.DateField()
    #description=forms.CharField(widget=forms.Textarea)


class incomemodelform(forms.ModelForm):
    class Meta:
        model=Income
        fields=["income","income_type","income_date","description"]




account/models.py
from django.db import models

from django import forms

class Loginform(forms.Form):
    uname=forms.CharField(max_length=30,label="username")
    pswd=forms.CharField(max_length=30,label="password")

Expense/views.py
from django.shortcuts import render, redirect
from .models import *

def addexpense(request):
    if request.method=="POST":
        obj=expenseform(request.POST)
        obj.save()
        return redirect("/")
    else:
        d={"form":expenseform}
        return render(request,"form.html",d)

def details(request):
    obj=Expense.objects.all()
    d={'data1':obj}
    return render (request,"details1.html",d)



def delete(request,incid):
    obj=Expense.objects.get(id=incid)
    obj.delete()
    return redirect("/Inc-details")

def edit(request,incid):
    data=Expense.objects.get(id=incid)
    if request.method=="POST":
        obj=expenseform(request.POST,instance=data)
        obj.save()
        return redirect("/")
    else:
        d={"form":expenseform(instance=data) }
        return render(request,"form.html",d)            

Income/views.py
from django.shortcuts import render, redirect

from .models import *
from django.contrib.auth.models import User


def addincome(request):
    if request.method == "POST":
        # income=request.POST.get("income")
        # income_type=request.POST.get("income_type")
        # income_date=request.POST.get("income_date")
        # description=request.POST.get("description")
        # user_id=request.session.get("id")
        # obj_user=User.objects.get(id=user_id)
        # obj=Income()
        # obj.income=income
        # obj.income_type=income_type
        # obj.income_date=income_date
        # obj.description=description
        # obj.user=obj_user
        user_id = request.session.get("id")
        obj_user = User.objects.get(id=user_id)
        obj=incomemodelform(request.POST)
        data=obj.save(commit=False)
        data.user=obj_user
        obj.save()
        return redirect("/")
    else:
        #d = {"form": incomeform}
        d={"form":incomemodelform}
        return render(request, "form.html", d)


def details(request):
    obj = Income.objects.all()
    d = {'data': obj}
    return render(request, "details.html", d)


def delete(request, incid):
    obj = Income.objects.get(id=incid)
    obj.delete()
    return redirect("/Inc-details")


def edit(request, incid):
    data = Income.objects.get(id=incid)
    if request.method == "POST":
        obj = incomemodelform(request.POST, instance=data)
        obj.save()
        return redirect("/")
    else:
        d = {"form": incomemodelform(instance=data)}
        return render(request, "form.html", d)

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm

from  django.contrib.auth import login, logout, authenticate
from .models import *

def home(request):
    return render(request,"home.html")


def register(request):
    if request.method=="POST":
        obj=UserCreationForm(request.POST)
        obj.save()
        return redirect("/")
    else:
        d={"form":UserCreationForm}
        return render(request,"form.html",d)
    
def loginn(request):
    if request.method=="POST":
        uname=request.POST.get("uname")
        pswd=request.POST.get("pswd")
        user=authenticate(request,username=uname,password=pswd)
        if user is not None:
            request.session["id"]=user.id
            print(request.session.get("id"))
            login(request,user)
            return redirect("/")
        else:
            d={"form":Loginform}
            return render(request,"form.html",d)
    else:
            d={"form":Loginform}
            return render(request,"form.html",d)
def logoutt(request):
    logout(request)
    return redirect("/")        
                
    



Expense/templates/details1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
{%extends 'sidebar.html'%}


{%block "body"%}
    <table border="1px" align="center" >
        <tr>
            <th>Expense</th>
            <th>Expense Type</th>
            <th>Expense Date</th>
            <th>Descrption</th>
            <th>user</th>
            <th colspan="2">Action</th>
        </tr>
        {% for i in data1 %}
        <tr>
            <td>{{i.expense}}</td>
            <td>{{i.expense_type}}</td>
            <td>{{i.expense_date}}</td>
            <td>{{i.description}}</td>
            <td>{{i.user}}</td>
            <td><a href="{%url 'expense:delete' i.id%}">Delete</a></td>
            <td><a href="{%url 'expense:edit' i.id%}">Edit</a></td>
        </tr>
        {%endfor%}
    </table>
    {%endblock%}
</body>
</html>

Income/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>


<body>

    {%extends 'sidebar.html'%}


    {%block "body"%}    
    <table border="1px" align="center" >
        <tr>
            <th>Income</th>
            <th>Income Type</th>
            <th>Incone Date</th>
            <th>Descrption</th>
            <th>user</th>
            <th colspan="2">Action</th>
        </tr>
        {% for i in data %}
        <tr>
            <td>{{i.income}}</td>
            <td>{{i.income_type}}</td>
            <td>{{i.income_date}}</td>
            <td>{{i.description}}</td>
            <td>{{i.user}}</td>
            <td><a href="{%url 'income:delete' i.id%}">Delete</a></td>
            <td><a href="{%url 'income:edit' i.id%}">Edit</a></td>
        </tr>
        {%endfor%}
    </table>
    {%endblock%}
</body>
</html>

account/templates/form.html
{%extends 'sidebar.html'%}


{%block "body"%}
<form method="post">
    {%csrf_token%}
    <table border="1px">
        {{form.as_table}}
        <tr>
            <td><input type="submit"></td>
            <td><input type="reset"></td>
        </tr>

    </table>

</form>
{%endblock%}

account/templates/home.html

{%extends 'sidebar.html'%}


{%block "body"%}


<h1 >Daily Expense Management</h1>
<h1>welcome {{user}}</h1>

{%endblock%}

account/templates/sidebar.html
{%load static%}
<link rel="stylesheet" href="{%static 'css/main.css' %}">
<div class="side">
    <h1><a href="/">Home</a></h1>
    <h1><a href="">About us</a></h1>
    {%if user.is_authenticated %}
    <h1><a href="{%url 'income:addincome'%}">AddIncome</a></h1>
    <h1><a href="{%url 'expense:addexpense'%}">AddExpense</a></h1>
    <h1><a href="{%url 'income:incdetails'%}">Incomelist</a></h1>
    <h1><a href="{%url 'expense:expdetails'%}">Epenselist</a></h1>
    <h1><a href="{%url 'account:logout' %}">Logout</a></h1>
    {%else%}
    <h1><a href="{%url 'account:register' %}">Register</a></h1>
    <h1><a href="{%url 'account:login'%}">Login</a></h1>
    {% endif %}
    

</div>
<div class="main">
{%block "body"%}  


{%endblock%}
</div>